### PR TITLE
Pure Bootique bootstrap of Cayenne projects #15

### PR DESCRIPTION
**Pull request by atomashpolskiy**
@andrus , please take a look

Everything seems fine except for DataMap names. I had to add a `map.name` attribute in config defaulting to DataMap's `URL.toExternalForm()` in case the name is not specified. For obvious reasons it's a rather poor strategy, so I hoped you could come up with a better one. Keep in mind that (1) we don't always have the DataMap file's name (e.g. in case with HTTP) and (2) different DataMaps may have the same file's name.

### CODE REVIEW

**Comment by atomashpolskiy** [comment]
Weird, all tests passed before I commited... I'll take another look

**Comment by andrus** [comment]
Implementation looks good, but the test is failing. I am getting the same error as Travis here.

**Comment by atomashpolskiy** [comment]
@andrus , turns out `SchemaUpdateStrategy` is shared among all DataNodes (or something like that) and performs update only once (see `org.apache.cayenne.access.dbsync.BaseSchemaUpdateStrategy#updateSchema`). I've managed to fix this, but the solution clearly is a hack.

**Comment by andrus** [comment]
> (see org.apache.cayenne.access.dbsync.BaseSchemaUpdateStrategy#updateSchema)

Clearly a bug. We need to fix it in Cayenne... Let me take a shot.

**Comment by andrus** [comment]
Regarding the PR... We are still creating more DataNodes than we have DataSources, no?

**Comment by andrus** [comment]
@atomashpolskiy : I am in the process of fixing the issue in Cayenne per [CAY-2125](https://issues.apache.org/jira/browse/CAY-2125). But here is how to fix it in bootique-cayenne until we can upgrade to M4:

```java
if(/*schema generation required*/
     nodeDescriptor.setSchemaUpdateStrategyType(CreateIfNoSchemaStrategy.class.getName());
```
I.e. if update strategy is explicitly present in descriptor, Cayenne would create an instance of this strategy for a given DataNode without sharing. So the issue should go away.

**Comment by atomashpolskiy** [comment]
> Regarding the PR... We are still creating more DataNodes than we have DataSources, no?
No

> I.e. if update strategy is explicitly present in descriptor, Cayenne would create an instance of this strategy for a given DataNode without sharing. So the issue should go away.
Thanks, this was exactly what I've done

**Comment by andrus** [comment]
> Thanks, this was exactly what I've done

I overlooked this somehow. Yep, this is the correct solution.

> >  Regarding the PR... We are still creating more DataNodes than we have DataSources, no?
> No

From what I see , Nodes are created in the loop for each map config? Plus one extra node is added added above the loop inside ```if (dataDomain.getDataNodes().isEmpty()) {``` block.

**Comment by atomashpolskiy** [comment]
> From what I see , Nodes are created in the loop for each map config? Plus one extra node is added added above the loop inside if (dataDomain.getDataNodes().isEmpty()) { block.

Yeah, there is a loop, but it iterates over the result of `getDataMapConfigs():Map<String, Collection<DataMapConfig>>`, that groups configs by the name of the datasource (with proper fallback to the default datasource if needed).

**Comment by andrus** [comment]
I am getting blind :) Sorry. What about the default node added per ```if (dataDomain.getDataNodes().isEmpty())```?

**Comment by atomashpolskiy** [comment]
> I am getting blind :) Sorry.

No worries, happens to me all the time.

> What about the default node added per if (dataDomain.getDataNodes().isEmpty())?

Well, this is needed in case we've got some configs (contributed via `configs` key), which contain only references to DataMaps. Though it seems like I accidentally removed an additional `!dataDomain.getDataMaps().isEmpty()` check while experimenting. This check should prevent creation of an empty DataNode if there are no maps.

**Comment by andrus** [comment]
What about the case when default DataNode is mapped to the same DataSource as one of the map configs? Will we end up with 2 DataNodes with the same DataSource?

**Comment by atomashpolskiy** [comment]
> What about the case when default DataNode is mapped to the same DataSource as one of the map configs? Will we end up with 2 DataNodes with the same DataSource?

Yeah, you're right. I'll fix this tomorrow

**Comment by atomashpolskiy** [comment]
@andrus , fixed and checked

**Pull request merged**
